/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pbogradleencryptor;

public class App {

    public static void main(String[] args) throws Exception {
        PasswordStore ps = new PasswordStore(
                "Nurudin Wafiq",
                "wafiq",
                "gedanggoreng",
                PasswordStore.CAT_MOBILEAPP);

        System.out.println(ps.toString());
        System.out.println("Password Aseli: " + ps.getPassword());
    }
}
